name: 'replica-apartment2'
notes: '
  [Data] apartment_2
  [Model] 500 planes, radiance field, from scratch
  [init] dense points (w/ box)
  [Loss] mse_color + mse_point2plane (dense + depth pred.)
  [Reg.] oscillate NDC
'
cuda: '0'
checkpoint: ''
model:
  plane_num: 500
  init:
    lrf_neighbors: 100
    wh: 1
    box_factor: 4
    random_rate: 0.0
  n_harmonic_functions_pos: 10
  n_harmonic_functions_dir: 4
  n_hidden_neurons_pos: 256
  n_hidden_neurons_dir: 128
  n_layers: 8
  n_train_sample: 4096
  n_infer_sample: 4096
  anti_aliasing: True
  premultiply_alpha: False
  n_bake_sample: 10000
  bake_res: 1024
  filter_bar: 0.01
  bake: False
data:
  path: 'data/replica/apartment_2/'
  image_size: [512, 512]
  sample_points: 10000
  white_bg: False

loss_weight:
  color: 1.0
  depth: 0.0
  point2plane: 1.0
  area: 0.00000001
  alpha: 0.0
optimizer:
  lr: 0.0005
  lr_scheduler_step_size: 5000
  lr_scheduler_gamma: 0.1

train:
  resume: True
  epoch: 2000
  validation_epoch: 200
  checkpoint_epoch: 100
test:
  mode: 'test_model'
  folder: ''
  vis:
    id: ''
    r: 3
    c: [0.5, 0.5, 0.5]
    alpha: 0.3
seed: 0

# finetune:
#   epoch: 200
#   validation_epoch: 1000
#   checkpoint_epoch: 100
#   checkpoint_target: '1101-apartment2-exp0-fast.pth'