name: 'tat-barn'
notes: ' 
  model white background
  [Data] T&T(nb) Barn, white background
  [Model] 400 planes, radiance field, from scratch
  [init] dense points (w/o box)
  [Loss] mse_color + mse_point2plane (dense) + area_reg.
  [Reg.] oscillate NDC
'
cuda: '0'
checkpoint: ''
model:
  plane_num: 1000
  init:
    lrf_neighbors: 100
    wh: 0.3
    box_factor: 2
    random_rate: 0.9
  n_harmonic_functions_pos: 10
  n_harmonic_functions_dir: 4
  n_hidden_neurons_pos: 256
  n_hidden_neurons_dir: 128
  n_layers: 8
  n_train_sample: 10000
  n_infer_sample: 10000
  anti_aliasing: True
  premultiply_alpha: False
  n_bake_sample: 10000
  bake_res: 1024
  filter_bar: 0.01
  bake: False
  learn_size: True
data:
  path: 'data/TanksAndTemple/Barn'
  image_size: [1080, 1920]
  sample_rate: 0.1
  batch_points: 10000
  white_bg: True

loss_weight:
  color: 1.0
  depth: 0.0
  point2plane: 1.0
  area: 0.00005
  alpha: 0.0
optimizer:
  lr: 0.0005
  lr_scheduler_step_size: 5000
  lr_scheduler_gamma: 0.1

train:
  resume: True
  epoch: 10000
  validation_epoch: 500
  checkpoint_epoch: 10
test:
  mode: 'test_model'
  folder: ''
  vis:
    id: ''
    r: 3
    c: [0.5, 0.5, 0.5]
    alpha: 0.3
seed: 0

video:
  traj_path: 'video/tanks/barn/traj_1'
  name: 'ours-barn-traj1'
  fps: 30

finetune:
  epoch: 200
  validation_epoch: 1000
  checkpoint_epoch: 100
  checkpoint_target: '1110-barn-exp0.pth'